WebApp/Controllers/AuthorizationController.cs
using System;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BLL.Repositories.User;
using BLL.DTO.UserDTO;
using Newtonsoft.Json;



namespace WebApp.Controllers
{
	[Authorize]
	public class AuthorizationController : Controller
    {
     
       private readonly IUserRepository userRepository;
	   private readonly LoginModelValidator validation;
    
        public AuthorizationController(IUserRepository userRepository,LoginModelValidator validation)
		{
			//this.userRepository = userRepository ?? throw new ArgumentNullException(nameof(userRepository));
			//this.validation = validation ?? throw new ArgumentNullException(nameof(validation));
			this.userRepository = userRepository;
			this.validation = validation;
		}

		[AllowAnonymous]
		public ActionResult Login()
        {
            return View();
        }


		[HttpPost]
		[AllowAnonymous]
		public async Task<ActionResult> Login(BLL.DTO.UserDTO.GetUserDTO model)
		{

			if (ModelState.IsValid)
			{

				var result = validation.Validate(model);

				if (!result.IsValid)
				{
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
					}
					return View(model); // return to the view with the validation errors
				}

				var user = userRepository.LoginUser(model.Login, model.Password);

				if (user == null)
				{
					ModelState.AddModelError("", "Invalid login attempt."); 
					return View(model);
				}



				else
				{
					string userData = JsonConvert.SerializeObject(user);

					var authTicket = new FormsAuthenticationTicket(1, user.Login, DateTime.Now, DateTime.Now.AddDays(15), false, userData);

					string encTicket = FormsAuthentication.Encrypt(authTicket);
					var faCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
					Response.Cookies.Add(faCookie);

					return RedirectToAction("Index", "Home");

				}
			}
			return View(model);
		}


		[HttpGet]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "Authorization");
        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		

        public HomeController()
        {  
        }

		[Authorize()]
        public ActionResult Index()
		{
			return View();
		}

		[Authorize]
		public ActionResult About()
		{
			ViewBag.Message = "Welcome back.";

			return View();
		}

		[Authorize]
		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

WebApp/Controllers/PosController.cs
using BBL.DTO.UserDTO.UserValidation;
using BLL.DTO.PosDTO;
using BLL.Repositories.Pos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    [Authorize]
    public class PosController : Controller
    {
        private readonly IPosRepository posRepository;
       
         
        public PosController(IPosRepository posRepository, AddUserValidation validation)
        {
             this.posRepository = posRepository;
            
        }
        
        // GET: Pos
        public ActionResult BrowsePos()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CreatePos() 
        {
            ViewBag.City = posRepository.GetAllCitites();
            ViewBag.ConType = posRepository.GetAllConnectionType();
          //  ViewBag.WeekDays = posRepository.
            return View();
        }
        [HttpPost]  
        public ActionResult CreatePos(AddPosDTO model)
        {
            if (ModelState.IsValid)
            {

     
				posRepository.AddPos(model);
			}
			ViewBag.City = posRepository.GetAllCitites();
			ViewBag.ConType = posRepository.GetAllConnectionType();
			return View();
        }
    }
}

WebApp/Controllers/UserController.cs
using BBL.DTO.UserDTO.UserValidation;
using BLL.DTO.UserDTO;
using BLL.Repositories.User;
using Newtonsoft.Json;
using System.Runtime.InteropServices;
using System.Web.Mvc;
using WebApp.Helpers;

namespace WebApp.Controllers
{
	[Authorize]
	public class UserController : Controller
    {

		private readonly IUserRepository userRepository;
		private readonly AddUserValidation validation;

		public UserController(IUserRepository userRepository,AddUserValidation validation)
		{
		
			this.userRepository = userRepository;
			this.validation = validation;
		}

		// GET: User
		[HttpGet]
		public ActionResult Browse()
        {
            return View();
        }

		[HttpGet]
		public JsonResult QueryUsers()
		{
			var criteria = Request.GetPaginatingCriteria();

			var users = userRepository.QueryUsers(criteria);

			var jsonData = new
			{
				draw = Request.QueryString["draw"],
				recordsTotal = users.Total,
				recordsFiltered = users.TotalFiltered,
				data = users.UserDTO
			};

			return Json(jsonData, JsonRequestBehavior.AllowGet);
		}


		[HttpGet]
		public ActionResult CreateUser()
	{
			ViewBag.UserTypes = userRepository.GetAllUsersType();
			return View();
		}
		[HttpPost]	
		public ActionResult CreateUser(AddUserDTO model)
		{
			if (ModelState.IsValid)
			{
				var result = validation.Validate(model);

				if (!result.IsValid)
				{
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
					}
					ViewBag.UserTypes = userRepository.GetAllUsersType();
					return View(model);
				}

				var user = userRepository.AddUser(model);

				return RedirectToAction("Browse");
			}

			ViewBag.UserTypes = userRepository.GetAllUsersType();
			return View(model);
		}

    }
}

WebApp/Views/Authorization/Login.cshtml
@model BLL.DTO.UserDTO.GetUserDTO

@{
    ViewBag.Title = "Registration";
    Layout = null;
}




@using (Html.BeginForm("Login", "Authorization", FormMethod.Post, new { id = "login-form", @class = "login-form" }))
{
    

    <h1>Welcome to Libra</h1>
    <div class="form-group">
        @Html.LabelFor(model => model.Login, new { @class = "control-label" })
        @Html.EditorFor(model => model.Login)
        @Html.ValidationMessageFor(model => model.Login)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, new { @class = "control-label" })
        @Html.PasswordFor(model => model.Password)
        @Html.ValidationMessageFor(model => model.Password)
    </div>

    <div class="form-group">
        <input type="submit" value="Login" class="btn" />
    </div>
}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        align-items: center;
        background: #f4f4f4;
    }

    .login-form {
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        width: 300px; /* Sau orice altă lățime preferată */
        display: flex;
        flex-direction: column;
    }

    .form-group {
        width: 100%;
        margin-bottom: 15px;
    }

    .control-label {
        margin-bottom: 5px;
        text-align: center;
    }

    input[type="text"], input[type="password"], input[type="submit"] {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    input[type="submit"] {
        background-color: #4CAF50;
        color: white;
        cursor: pointer;
    }

        input[type="submit"]:hover {
            background-color: #45a049;
        }
</style>

WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

WebApp/Views/Pos/CreatePos.cshtml
@model BLL.DTO.PosDTO.AddPosDTO
@{
    ViewBag.Title = "CreatePos";
}

<h2>CreatePos</h2>

<!-- page content -->

@using (Html.BeginForm("CreatePos", "Pos", FormMethod.Post, new { id = "login-form", @class = "login-form" }))
{
    <div class="left_col-" role="main">
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-12">
                    <div class="x_panel" style="width: 105vh;">
                        <div class="x_title">
                            <h4>
                                User Data
                            </h4>
                        </div>
                        <div class="x_content">
                            <br />
                            <form id="demo-form2" data-parsley-validate
                                  class="form-vertical form-label-left">

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.Telephone, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Telephone)
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.CellPhone, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.EditorFor(model => model.CellPhone, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.CellPhone, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Address)
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.City_Id, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            <select id="UserTypeId" name="UserTypeId" class="select2_single form-control">
                                                <option value="">-- Select User Type --</option>
                                                @foreach (var city in ViewBag.City)
                                                {
                                                    <option value="@city.Id">@city.Name</option>
                                                }
                                                @Html.ValidationMessageFor(model => model.City_Id)
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.Brand, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Brand)
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.Model, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Model)
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.ConnectionType, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            <select id="UserTypeId" name="UserTypeId" class="select2_single form-control">
                                                <option value="">-- Select User Type --</option>
                                                @foreach (var conType in ViewBag.ConType)
                                                {
                                                    <option value="@conType.Id">@conType.ConectionType</option>
                                                }
                                                @Html.ValidationMessageFor(model => model.ConnType_Id)
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.MorningOperning, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.TextBoxFor(model => model.MorningOperning, new { @class = "form-control", @type = "time" })
                                            @Html.ValidationMessageFor(model => model.MorningOperning, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.MorningClosing, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.TextBoxFor(model => model.MorningClosing, new { @class = "form-control", @type = "time" })
                                            @Html.ValidationMessageFor(model => model.MorningClosing, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.AfternoonOpening, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.TextBoxFor(model => model.AfternoonOpening, new { @class = "form-control", @type = "time" })
                                            @Html.ValidationMessageFor(model => model.AfternoonOpening, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        @Html.LabelFor(model => model.AfternonClosing, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                        <div class="col-md-6 col-sm-6 col-12">
                                            @Html.TextBoxFor(model => model.AfternonClosing, new { @class = "form-control", @type = "time" })
                                            @Html.ValidationMessageFor(model => model.AfternonClosing, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>




                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-md-6 col-sm-6 col-12 col-md-offset-3">
                                            <button type="submit" value="CreatePos" class="btn btn-success" style="color: #fff;">
                                                Create new POS
                                            </button>
                                        </div>

                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>Libra!</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="~/Content/datatables.min.css" rel="stylesheet">
    <link href="~/Content/custom.min.css" rel="stylesheet">

    <style>

        body {
            background-color: #FFFFFF;
        }

        .nav-md .container.body .main_container {
            background-color: #FFFFFF;
        }
    </style>
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="index.html" class="site_title">
                        <i class="fa fa-paw"></i> <span>Libra Dashboard!</span>
                    </a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                    </div>
                    <div class="profile_info">
                        <span>Welcome,</span>
                        <h2>@User.Identity.Name </h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">

                        <ul class="nav side-menu">
                            <li>
                                <a href="#">
                                    <i class="fa fa-tachometer" aria-hidden="true"></i>Dashboard <span class="fa fa-chevron-down"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#"><i class="fa fa-edit"></i> POS <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li>
                                        @Html.ActionLink("Add POS", "CreatePos", "Pos", null, new { @class = "nav-link" })
                                    </li>
                                    <li> @Html.ActionLink("Browse", "BrowsePos", "Pos", null, new { @class = "nav-link" }) </li>
                                </ul>
                            </li>
                            <li>
                                <a><i class="fa fa-desktop"></i> Issues <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li>
                                        <a href="general_elements.html">Add Issues</a>
                                    </li>
                                    <li>
                                        <a href="media_gallery.html">Browse Issues</a>
                                    </li>

                                </ul>
                            </li>
                            <li>
                                @if (User.IsInRole("admin"))
                                {
                                    <a><i class="fa fa-table"></i> Users<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li>
                                            @Html.ActionLink("Add User", "CreateUser", "User", null, new { @class = "nav-link" })
                                        </li>
                                        <li>
                                            @Html.ActionLink("Browse User", "Browse", "User", null, new { @class = "nav-link" })
                                        </li>
                                    </ul>
                                }
                            </li>
                            }
                        </ul>
                    </div>
                </div>

            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <div class="nav toggle">
                    <a id="menu_toggle">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>
                <nav class="nav navbar-na pull-right">
                    <ul class=" navbar-right">
                        <li class="nav-item dropdown open">
                            <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">

                                @User.Identity.Name
                            </a>
                            <span style="margin-left :10px;"></span>
                            @Html.ActionLink("Logout", "LogOff", "Authorization", null, new { @class = "nav-link" })
                        </li>

                    </ul>
                </nav>
            </div>
        </div>

        <!-- page content -->
        <div class="right_col" role="main">
            <div class="">
                <div class="page-title">
                    <div class="title_left">
                        <h3>Dashboard </h3>
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->

    </div>
</div>

<!-- jQuery -->
<script src="~/Scripts/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/Scripts/bootstrap.bundle.min.js"></script>


@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/custom")
@RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/User/CreateUser.cshtml
@model @BLL.DTO.UserDTO.AddUserDTO 
@{
    ViewBag.Title = "CreateUser";
}

<h1>CreateUser</h1>

<!-- page content -->

@using (Html.BeginForm("CreateUser", "User", FormMethod.Post, new { id = "login-form", @class = "login-form" }))
{
  <div class="left_col-" role="main">
    <div class=""> 
        <div class="clearfix"></div>
          <div class="row">
            <div class="col-md-12 col-sm-12 col-12">
                <div class="x_panel" style="width: 105vh;">
                    <div class="x_title">
                        <h4>
                            User Data
                        </h4> 
                    </div>
                    <div class="x_content">
                        <br />
                        <form id="demo-form2" data-parsley-validate
                              class="form-vertical form-label-left">

                            <div class="form-group">
                                <div class="row">
                                    @Html.LabelFor(model => model.Login, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                    <div class="col-md-6 col-sm-6 col-12">
                                         @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })

                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                    <div class="col-md-6 col-sm-6 col-12">
                                        @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Password ,"", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                    <div class="col-md-6 col-sm-6 col-12">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name , "",new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    @Html.LabelFor(model => model.Telephone, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                    <div class="col-md-6 col-sm-6 col-12">
                                        @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Telephone ,"", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                    <div class="col-md-6 col-sm-6 col-12">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email ,"", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    @Html.LabelFor(model => model.UserTypeId, new { @class = "control-label col-md-3 col-sm-3 col-12" })
                                    <div class="col-md-6 col-sm-6 col-12">
                                        <select id="UserTypeId" name="UserTypeId" class="select2_single form-control">
                                            <option value="">-- Select User Type --</option>
                                            @foreach (var userType in ViewBag.UserTypes)
                                            {
                                                <option value="@userType.Id">@userType.UserType</option>
                                            }
                                            @Html.ValidationMessageFor(model => model.UserTypeId, "", new { @class = "text-danger" })
                                        </select>

                                    </div>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-6 col-sm-6 col-12 col-md-offset-3">
                                        <button class="btn btn-primary" type="button" style="color: #fff;">
                                            @Html.ActionLink("Cancel", "Browse", "User", null, new { @class = "nav-link" })
                                        </button>
                                        <button type="submit" value="CreateUser" class="btn btn-success" style="color: #fff;">
                                            Save changes
                                        </button>
                                    </div>

                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
         </div>  
    </div>
 </div>
}